version: '3'

networks:
  backend-dev:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend-dev
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    networks:
      - backend-dev

  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./docker/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./docker/mysql/dump:/home/root/dump
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    cap_add:
        - SYS_NICE
        - SYS_RESOURCE
    networks:
      - backend-dev